# Notes:
# 1.	This workflow triggers on pushes to main or master and on pull requests.
# 2.	It builds the Docker image from your repository.
# 3.	The image is tagged as ghcr.io/<your-username>/latex-docker:latest.
# 4.	It logs into GHCR using the built-in GITHUB_TOKEN and pushes the image.
name: Build and Publish LaTeX Docker Image

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Required to push to GHCR

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Convert GitHub Username to Lowercase
        run: echo "USERNAME_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ env.USERNAME_LOWER }}/latex-docker:latest .

      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/${{ env.USERNAME_LOWER }}/latex-docker:latest

      - name: Set Image to Public
        run: |
          gh api -X PATCH https://api.github.com/user/packages/container/latex-docker/visibility \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -F visibility:public